apiVersion: v1
kind: Service
metadata:
  name: tool-chain
  labels:
    app: oes
    component: oes-toolchain
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.toolchain.serviceAnnotations }}
  annotations:
{{ toYaml .Values.toolchain.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: tool-chain
      protocol: TCP
      port: 8100
      targetPort: 8100
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8100
      {{- end }}
  selector:
    app: oes
    component: oes-toolchain