{{- if (eq .Values.installationMode "SSD-SPIN") -}}
apiVersion: v1
kind: Service
metadata:
  name: supplychain-api
  labels:
    app: oes
    component: oes-supplychain-api
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.supplychainapi.serviceAnnotations }}
  annotations:
{{ toYaml .Values.supplychainapi.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
    - name: supplychain-api
      protocol: TCP
      port: 8099
      targetPort: 8099
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8099
      {{- end }}
  selector:
    app: oes
    component: oes-supplychain-api
{{- end -}}
