apiVersion: v1
kind: Service
metadata:
  name: ssd-opa
  labels: 
    app: oes
    component: oes-ssd-opa
spec:
  selector:
    app: oes
    component: oes-ssd-opa
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.ssdopa.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ssdopa.serviceAnnotations | indent 4 }}
{{- end }}    
  ports:
    - name: ssd-opa
      protocol: TCP
      port: 8200
      targetPort: 8200
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8200
      {{- end }}
    
