{{- if (eq .Values.installationMode "SSD-SPIN") -}}
apiVersion: v1
kind: Secret
metadata:
  name: ssd-opa
  labels:
    app: ssd
{{ include "oes.standard-labels" . | indent 4 }}
    component: oes-ssd-opa
stringData:
{{ (tpl (.Files.Glob "config/oes-ssd-opa/ssd-opa.yaml").AsConfig . ) | indent 2 }}
{{- end -}}
