apiVersion: v1
kind: Service
metadata:
  name: supplychain-preprocessor
  labels:
    app: oes
    component: supplychain-preprocessor
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.supplychainpreprocessor.serviceAnnotations }}
  annotations:
{{ toYaml .Values.supplychainpreprocessor.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  ports:
  - name: supplychain-preprocessor
    port: 8058
    protocol: TCP
    targetPort: 8058
      {{- if eq .Values.k8sServiceType "NodePort" }}
      nodePort: 8058
      {{- end }}    
  selector:
    app: oes
    component: supplychain-preprocessor
