apiVersion: v1
kind: Service
metadata:
  name: tool-chain
spec:
  selector:
    app: oes
    component: tool-chain
  ports:
    - name: tool-chain
      protocol: TCP
      port: 8100
      targetPort: 8100
    
