apiVersion: v1
kind: ServiceAccount
metadata:
  name: dgraph-schema-configure-{{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dgraph-schema-configure-{{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dgraph-schema-configure-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dgraph-schema-configure-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: dgraph-schema-configure-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
