opaIngress: https://{{ .Values.ssdopa.ingress.host }}
httpListenPort: 8200
kubescapeFilePath: /app/kubescapeDir
toolChainAddr: http://tool-chain:8100/ #default value & optional
graphQLAddr: http://dgraph-public:8080/graphql #default value & optional
openSSFFilePath: /app/OpenSSF #default value & optional
semgrepFilePath: /app/semgrep #default value & optional
sonarQubeAddr: https://sonar.opsmx.com/
reScheduleDays: 1
reScheduleTime: 00:00
databases:
  ssd:
    connectString: host=oes-db user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=ssddb port=5432
