ssdIngress: {{.Values.global.ssdUI.protocol}}://{{.Values.global.ssdUI.host}}
detectorImage: quay.io/opsmxpublic/kubernetes-detector:v1.0.2
tokenMachine:
    host: http://token-machine
    port: 8050
opsMxSvc: {{.Values.global.ssdUI.protocol}}://{{.Values.global.ssdUI.host}}
ssdOpa: http://ssd-opa:8200
redis: {{ template "ssd.redisBaseURL" . }}
graphqlsvc:
    host: http://dgraph-public
    port: 8080
postgresql:
    ssd:
      connectString: host={{ .Values.db.host }} user='{{ .Values.db.username }}'  password='{{ .Values.db.password }}' database=ssddb port={{ .Values.db.port }}
toolchain:
    host: http://tool-chain
    port: 8100
spinnaker:
    rabbitmq:
      username: '{{ .Values.rabbitmq.username }}'
      password: '{{ .Values.rabbitmq.password }}'
      host: rabbitmq-service
      port: 5672
      queue: preview-saas-ssd
      #queue: isd-to-preview-saas
      exchange: echo.events
      bindingKey: preview-saas-ssd
