integrationData:
  - stage: Source
    integrations:
      - integratorType: gitlab
        displayName: Gitlab
        multiSupport: false
        category: sourcetool
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: API URL
            dataType: input
            required: true
            secret: false
            helpText: Gitlab Host URL
            placeholderText: 'Example:https://gitlab.com'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: false
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: github
        displayName: Github
        multiSupport: false
        category: sourcetool
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: API URL
            dataType: input
            required: true
            secret: false
            helpText: GitHub Host URL
            placeholderText: 'Example:https://github.com'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: false
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: bitbucket
        displayName: BitBucket
        multiSupport: false
        category: sourcetool
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: API URL
            dataType: input
            required: true
            secret: false
            helpText: BitBucket Host URL
            placeholderText: 'Example:https://bitbucket.com'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: false
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: sonarqube
        displayName: Sonarqube
        multiSupport: false
        category: sourcetool
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: URL
            dataType: input
            required: true
            secret: false
            helpText: Sonarqube Host URL
            placeholderText: 'Example:https://sonarqube.com'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: openssf
        displayName: OpenSSF
        multiSupport: false
        category: scanningtool
        testConnectionFlag: false
        configurationFields:
          compliancescan:
            displayName: Compliance Scan
            dataType: checkbox
            required: true
            secret: false
            helpText: Enable/Disable
            placeholderText: 'Example:Compliance Scan'
            data:
              - Compliance Scan
      - integratorType: semgrep
        displayName: SemGrep
        multiSupport: false
        category: sourcetool
        testConnectionFlag: false
        configurationFields:
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
          sastdastscan:
            displayName: Sast/Dast scan
            dataType: checkbox
            required: true
            secret: false
            helpText: Enable/Disable
            placeholderText: 'Example:Helm Scan'
            data:
              - Sast/Dast scan
  - stage: Build
    integrations:
      - integratorType: jenkins
        displayName: Jenkins
        multiSupport: true
        category: citool
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: Host Url
            dataType: input
            required: true
            secret: false
            helpText: Jenkins Host URL
            placeholderText: 'Example:https://org.myjenkin.com/jenkins'
          builduser:
            displayName: Approved Build User
            dataType: chipset
            required: true
            secret: false
            helpText: build_username
            placeholderText: 'Example:approved_build_username'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:username-Password/username-Token'
            authType:
              - basic
  - stage: Artifact
    integrations:
      - integratorType: trivy
        displayName: Trivy
        multiSupport: false
        category: scanningtool
        testConnectionFlag: false
        configurationFields:
          scantype:
            displayName: Scan Type
            dataType: checkbox
            required: true
            secret: false
            helpText: Scan Type
            placeholderText: >-
              Example:License Scan/Helm Scan/Vulnerability Scan
            data:
              - License Scan
              - Secret Scan for Source Code
              - Secret Scan for Containers
              - Vulnerability Scan
              - Helm Scan
      - integratorType: docker
        displayName: Docker
        multiSupport: true
        category: dockerregistry
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: Host Url
            dataType: input
            required: true
            secret: false
            helpText: Docker Host URL
            placeholderText: 'Example:https://docker.io'
          repo:
            displayName: Approved Artifact Repo
            dataType: chipset
            required: false
            secret: false
            helpText: Repo Name
            placeholderText: 'Example:dockerhub'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:username/password'
            authType:
              - basic
      - integratorType: quay
        displayName: Quay
        multiSupport: true
        category: dockerregistry
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: Host Url
            dataType: input
            required: true
            secret: false
            helpText: Quay Host URL
            placeholderText: 'Example:https://quay.io'
          repo:
            displayName: Approved Artifact Repo
            dataType: chipset
            required: false
            secret: false
            helpText: Repo Name
            placeholderText: 'Example:quayrepo'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:username/password'
            authType:
              - basic
      - integratorType: jfrog
        displayName: JFrog
        multiSupport: true
        category: dockerregistry
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: Host Url
            dataType: input
            required: true
            secret: false
            helpText: JFrog Host URL
            placeholderText: 'Example:https://jfrogartifactory.io'
          repo:
            displayName: Approved Artifact Repo
            dataType: chipset
            required: false
            secret: false
            helpText: Repo Name
            placeholderText: 'Example:jfrog'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:username/password'
            authType:
              - basic
      - integratorType: google-artifact-registry
        displayName: Google Artifact Registry
        category: aptregistry
        configurationFields:
          key:
            displayName: Service Account Key
            dataType: input
            required: false
            secret: false
            helpText: service account json only required for private
            placeholderText: '{sample}'
          source:
            displayName: Source
            dataType: chipset
            required: true
            secret: false
            helpText: entire source
            placeholderText: 'deb https://<REGION>-apt.pkg.dev/projects/<PROJECTID> <REPONAME> main'
      - integratorType: grype
        displayName: Grype (CMD)
        multiSupport: false
        category: dockerregistry
        testConnectionFlag: true
        configurationFields:
          vulnerabilityScan:
            displayName: Vulnerability Scan
            dataType: checkbox
            required: true
            secret: false
            helpText: Enable/Disable
            placeholderText: 'Example:Vulnerability Scan'
            data:
              - Vulnerability Scan
      - integratorType: snyk
        displayName: Snyk
        multiSupport: false
        category: scanningtool
        testConnectionFlag: true
        configurationFields:
          auth:
            displayName: Auth Type
            dataType: auth
            required: false
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
          helmscan:
            displayName: Helm Scan
            dataType: checkbox
            required: true
            secret: false
            helpText: Enable/Disable
            placeholderText: 'Example:Helm Scan'
            data:
              - Helm Scan
  - stage: Others
    integrations:
      - integratorType: chatgpt
        displayName: ChatGPT
        multiSupport: false
        category: communications
        testConnectionFlag: true
        configurationFields:
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: slack
        displayName: Slack
        multiSupport: false
        category: communications
        testConnectionFlag: true
        configurationFields:
          channel:
            displayName: Channel
            dataType: input
            required: true
            secret: false
            helpText: Slack Channel Name
            placeholderText: 'Example:channel_name'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: jira
        displayName: Jira
        multiSupport: false
        category: communications
        testConnectionFlag: true
        configurationFields:
          projectKey:
            displayName: Jira Project Key
            dataType: input
            required: true
            secret: false
            helpText: Jira Project Key
            placeholderText: 'Example:KAN'
          username:
            displayName: Jira Username
            dataType: input
            required: true
            secret: false
            helpText: Jira Host URL
            placeholderText: 'Example:https://your.domain.net'
          url:
            displayName: Jira URL
            dataType: input
            required: true
            secret: false
            helpText: Jira Host URL
            placeholderText: 'Example:https://your.domain.net'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: false
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
      - integratorType: custompolicy
        displayName: Custom Policy Source
        multiSupport: false
        category: managementtool
        testConnectionFlag: true
        configurationFields:
          url:
            displayName: Repo URL & Path
            dataType: input
            required: true
            secret: false
            helpText: Custom Policy Source Path
            placeholderText: 'Example:https://github.com/abc/def'
          auth:
            displayName: Auth Type
            dataType: auth
            required: true
            secret: true
            helpText: Authentiation Type
            placeholderText: 'Example:knjnasjwokldjhse'
            authType:
              - apiKey
