apiVersion: v2
name: ssd
version: "2024.04.02"
appVersion: "2024.04.00"
description: "OpsMx Secure Software Delivery for CI/CD Pipelines"
icon: https://raw.githubusercontent.com/OpsMx/enterprise-spinnaker/master/img/opsmx.png
maintainers:
- email: srinivas@opsmx.io
  name: Srinivas K
- email: saiteja.katabhatina@opsmx.io
  name: Sai Teja K
keywords:
  - OpsMx
  - SSD
home: https://www.opsmx.com/
dependencies:
  - name: dex
    version: 0.15.3
    condition: ssdgate.installDex
  - name: minio
    version: 8.0.9
    condition: global.minio.enabled
  - name: redis
    version: 10.5.3
    condition: installRedis
