#################This file is used to Install SSD with Inbuilt Authentication##########################
#####################################################
#k8sServiceType: LoadBalancer
####################################################
# Global variables can be accessed across all the charts including sub-charts
global:
  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  certManager:  # set to true if cert-manager is installed
    installed: true
  createIngress: true

  ssdUI: # URL used to access the application
    # Change to http if global.certManager.installed is false
    protocol: https
    ## Update the host value with proper dns entry to access the SSD UI
    host: SSD.REPLACE.THIS.WITH.YOURCOMPANY.COM

#############################################################################
### Change the Organisation name if user wants a different name in the UI
organisationname: opsmx

### Admin groups in SSD for Rbac #############################################
admingroups: admin
###############################################################################
#####User doesn't need to change the below flags let it be the default one######################
ssdgate:
  installDex: false   # Default will be false, Set to true if dex need to be installed
  auth_type: poclogin  # saml, dex-oidc and poclogin are other valid values
  admin_groups:
  - admin
  saml:
    saml_initiated_login: false
