#####################################################

# OpsMx Secure Software Delivery
#####################################################
## Info related to registry where OES images are stored
imageCredentials:
  repoUrl: https://quay.io/
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: quay.io/opsmxpublic

#storageClass: standard
# noPvc is true, no PVCs will be created, suitable for minikube
noPvc: false

AESEncryptionKey: OKPQK0JWS2TVTW9E86IWWYN3VY4Z34WJ
####################################################
## Redis configuration
## Set it to false only if SSD needs to be configured with external redis
installRedis: true
###################################################
# kubernetes services can be exposed to a web-UI based 3 modes
# ClusterIP (will required Ingress or some other mechanism)
# or LoadBalancer or NodePort
# OES UI, OES Gate, Spinnaker Deck and Spinnaker Gate service type
k8sServiceType: ClusterIP
UIServiceType: ClusterIP
RabbitServiceType: LoadBalancer  # Type for the Rabbit MQ, default is LB, can be changed to ClusterIP

#################################################
## Change the Organisation name if user wants a different name in the UI
organisationname: default

## Admin Groups for Rbac #######################
admingroups: admin
########################################
SSDMode: kubernetes
####################################################
# Global variables can be accessed across all the charts including sub-charts
global:
  # Custom Images registry where all the OSS and customized images used in the helm chart are stored
  # Only update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  customImages:
    registry: quay.io/opsmxpublic

  # when this flag is set to false; UI will be accessible over http instead of https
  # This does not appear to be used at all
  #ssl:
  #  enabled: false

  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  # Else, the TLS secrets will need to created manually
  certManager:
    installed: false

  customCerts:
    enabled: false        # Set to true if your organization requires custom TLS certs
    secretName: oes-cacerts # Please do not change this

  ## Set to true to expose oes-ui, oes-gate services over ingress
  createIngress: false

  ## OES-UI url configuration, defaults to http://localhost:8080
  ssdUI:
    protocol: http
    host: localhost
    # Use below port when hostname above is an external IP instead of a hostname
    #port: 8080

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/client-header-buffer-size: 100k
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
      tls:
        secretName: ssd-ui-ingress

  # Minio is needed for dGraph (till its need is removed)
  minio:
    enabled: true
    image:
      repository: quay.io/opsmxpublic/minio
      tag: RELEASE.2020-12-03T05-49-24Z  # RELEASE.2020-01-03T19-12-21Z
    mcImage:
      repository: quay.io/opsmxpublic/minio-mc
      tag: RELEASE.2020-11-25T23-04-07Z
    service:
      type: ClusterIP
    accessKey: spinnakeradmin
    secretKey: spinnakeradmin
    region: us-east-1
    #Below is the securityContext block for only for K8S
    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    buckets:
    - name: "ssd-temporal"
      policy: none
      purge: false
    defaultBucket:
      enabled: true
      name: "ssd-temporal"
    nodeSelector: {}
    affinity: {}
    tolerations: []
    persistence:
      enabled: true
      size: 10Gi
dgraph:
  image:
    repository: dgraph
    tag: v23.1.0
ratel:
  image:
    repository: ratel
    tag: v21.12.0
curl:
  image:
    repository: curl
    tag: 8.6.0
customLabels: {}
###############################################################################
ssdgate:
  image:
    repository: ssdgate
    tag: "2024-05-00"
  installDex: true
  createGateDexSecret: true
  #home_page: "/ui/index.html" # OPTIONAL default redirect page
  #session_timeout: 7200   # OPTIONAL login session timeout, it should match the authenticator timeout
  #skipstartcheck: true # OPTIONAL If true, pre-start checks will be skipped, well-known URL for OIDC cannot be used.
  #dex_url: "http://ssd-dex:5556" # OPTIONAL, Default is correct with OpsMx installed Dex

  auth_type: poclogin  # saml, dex_oidc and poclogin are other valid values
  admin_groups:
    - admin
  auth2_oidc:
    client_id: ssd-gate
    # kubectl create secret generic gate-dex-client-secret --from-literal client-secret=MYSECRET
    #client_secret: "encrypted:gate-dex-client-secret:client-secret" # Create a secret called gate-dex-client-secret with key client-secret
    entity_map:        # DEPENDS on the provider
      user_name: email #  Required for Dex
    #  roles: groups
    #well_known_url: http://my-well-known
    #redirect_url: "https//ssd-gate:8084/oidccallbackendpoint"       # OPTIONAL
    #userinfo_url: "https://dev-80355908.okta.com/oauth2/v1/userinfo"  # OPTIONAL
    # We need to "which field contains the username and roles"
    #endpoint:       # OPTIONAL Not required of well-known url is provided, else required
    #  auth_url: "https://dev-80355908.okta.com/oauth2/v1/authorize"
    #  token_url: "https://dev-80355908.okta.com/oauth2/v1/token"
    #scopes:         # OPTIONAL Not required of well-known url is provided, else required
    #  - openid      # openid MUST be specified, if used.
    #  - offline_access # It is best to leave offline_access in
    #  - email
    #  - roles
  saml:
    metadata_url: https://dev-14704582.okta.com/app/exkdnjuo0wxJsOtua5d7/sso/saml/metadata
    saml_initiated_login: true
    #entity_id: http://test-ssd.ryzon7-isd40.opsmx.org
    #sign_request: false # DEPENDS Default is false, make it match the SAML setting
    ## Optional files, create saml-files secret as follows, "saml-files" secret name should not be changed
    ## k create secret generic saml-files --from-file metadata.xml --from-file certificate.crt --from-file private.key
    #metadata_File: /app/saml/metadata.xml  # OPTIONAL One of metadata url or file required, url preferred
    #session_crt_file: /app/saml/certificate.crt # OPTIONAL
    #session_key_file: /app/saml/private.key #  OPTIONAL
    #entity_map: # OPTIONAL
    #  user_name: email  # Default is to take from the "subject" of the assertion. Use this to get it from an attribute
    #  roles: groups  # groups is default

###############################################################################
db:
  ## Set it to false if any external database is to be used
  enabled: true

  ## Change the default configuration when above option is set to false
  ## Below url and credentials are used by Autopilot & Sapor
  #url: jdbc:postgresql://oes-db:5432
  host: ssd-db
  port: 5432
  username: postgres
  password: networks123

  ## Image specific details
  image:
    repository: ssd-db
    tag: "2024-05-00"
    pullPolicy: IfNotPresent

  annotations: {}

  serviceAnnotations: {}

  ## Strategy to rollout statefulset pods
  podManagementPolicy: OrderedReady

  ## Default group to which the default user of a pod belongs and it applies only to K8S
  securityContext:
    fsGroup: 1000

  ## storageMountSize is the size with which a PVC is to be created
  storageMountSize: 8Gi

####################################################
toolchain:
  ## Image specific details
  image:
    repository: tool-chain
    tag: "2024-05-00"
    pullPolicy: IfNotPresent

  annotations: {}

  serviceAnnotations: {}

  securityContext: {}

  persistence:
    ## Change the pvc size as per the cluster requirements
    size: 50Gi
    accessMode: ReadWriteOnce

####################################################
supplychainpreprocessor:
  ## Image specific details
  image:
    repository: supplychain-preprocessor
    tag: "2024-05-00"
    pullPolicy: IfNotPresent

  annotations: {}

  serviceAnnotations: {}

  securityContext: {}

####################################################
ssdopa:
  ## Image specific details
  image:
    repository: ssd-opa
    tag: "2024-05-01"
    pullPolicy: IfNotPresent

  annotations: {}

  securityContext: {}

####################################################
supplychainapi:
  ## Image specific details
  image:
    repository: supplychain-api
    tag: "jul1"
    pullPolicy: IfNotPresent

  annotations: {}

  serviceAnnotations: {}

  securityContext: {}

######################################################
tokenmachine:
  ## Image specific details
  image:
    repository: token-machine
    tag: "2024-04-00"
    pullPolicy: IfNotPresent

  annotations: {}

  serviceAnnotations: {}

  securityContext: {}
###############################################################################
## Details of rabbitmq message bus image for SSD
##
rabbitmq:
  auth:
    username: rabbitmq
    password: "laPEifnlO51EE6e"
    securePassword: true
    existingPasswordSecret: ""
    existingSecretPasswordKey: ""

  service:
    type: LoadBalancer

  image:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: 3.13.3-debian-12-r0
    digest: ""
    debug: false
    pullPolicy: IfNotPresent
    ## Example:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
###############################################################################
## Values of SSD UI
ui:
  ## Image specific details
  image:
    repository: ssd-ui
    tag: "2024-05-02"
    pullPolicy: IfNotPresent

  annotations: {}

  serviceAnnotations: {}

  config:
    ## Interval, in millsecs, at which UI refreshes application dashboard
    setApplicationRefreshInterval: 300000

  securityContext:
    allowPrivilegeEscalation: false
##############################################################################
kubedetector:
  image:
    repository: kubernetes-detector
    tag: v1.0.1
kubescape:
  image:
    repository: kubescape-service
    tag: v0.0.1
#################################################################################

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
dex:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []
minio:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  topologySpreadConstraints: []

###############################################################################################
#### The values below this line are best not changed except in rare situations
###############################################################################################
dex:
  configSecret:
    create: false
    name: "gate-dex-config"
  volumes:
    - name: gate-dex-client-secret
      secret:
        defaultMode: 420
        secretName: gate-dex-client-secret
  env:
    - name: GATE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: gate-dex-client-secret
          key: client-secret
###############################################################################################
###  Redis Configuration
###############################################################################################
## Details of redis-master image for OES
redis:
  ## Redis endpoint that is used by oes-gate and oes-platform for caching;
  ## Change this to custom URL if installRedis is set to false
  ## url: redis://{{ .Release.Name }}-redis-master:6379
  url: redis://:password@{{ .Release.Name }}-redis-master
  port: 6379
  image:
    registry: quay.io/opsmxpublic
    repository: bitnami-redis
    tag: "2024-05-00"
  password: password
  cluster:
    enabled: false
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  # External Redis option will be enabled if in-cluster redis is disabled
  external:
    host: "<EXTERNAL-REDIS-HOST-NAME>"
    port: 6379
    # password: ""
  nodeSelector: {}
  master:
    affinity: {}
    tolerations: []

  ## Redis config file
  ## ref: https://redis.io/topics/config
  ##
  configmap: |-
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    appendonly no
    # Disable RDB persistence, AOF persistence already enabled.
    save 60 1000

  # Uncomment if you don't want to create a PVC for redis
  #  master:
  #    persistence:
  #      enabled: false
#########################################################################
temporal:
  server:
    image:
      repository: quay.io/opsmxpublic/temporal-server
      tag: 1.20.3
    config:
      persistence:
        default:
          driver: "sql"

          sql:
            driver: "postgres"
            host: ssd-db
            port: "5432"
            database: temporal
            user: postgres
            password: networks123
          # for a production deployment use this instead of `password` and provision the secret beforehand e.g. with a sealed secret
          # it has a single key called `password`
          # existingSecret: temporal-default-store
            maxConns: 20
            maxConnLifetime: "1h"
          # tls:
          #  enabled: true
          #  enableHostVerification: true
          #  serverName: _HOST_ # this is strictly required when using serverless CRDB offerings

        visibility:
          driver: "sql"

          sql:
            driver: "postgres"
            host: ssd-db
            port: "5432"
            database: temporal_visibility
            user: postgres
            password: networks123
          # for a production deployment use this instead of `password` and provision the secret beforehand e.g. with a sealed secret
          # it has a single key called `password`
          # existingSecret: temporal-visibility-store
            maxConns: 20
            maxConnLifetime: "1h"
          # tls:
          #  enabled: true
          #  enableHostVerification: true
          #  serverName: _HOST_ # this is strictly required when using serverless CRDB offerings

  web:
    image:
      repository: quay.io/opsmxpublic/temporal-ui
      tag: 2.9.0

  admintools:
    enabled: true
    image:
      repository: quay.io/opsmxpublic/temporal-admin-tools
      tag: 1.20.3

  cassandra:
    enabled: false

  mysql:
    enabled: false

  postgresql:
    enabled: true

  prometheus:
    enabled: false

  grafana:
    enabled: false

  elasticsearch:
    enabled: false

  schema:
    setup:
      enabled: false
    update:
      enabled: false
