apiVersion: v1
kind: Secret
metadata:
  name: supplychain-preprocessor
  labels:
    app: ssd
{{ include "oes.standard-labels" . | indent 4 }}
    component: oes-supplychain-preprocessor
stringData:
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/globalConfig.yml").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/jenkinsConfig.yml").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/spinnakerConfig.yml").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/argocdConfig.yml").AsConfig . ) | indent 2 }}
