apiVersion: v1
data:
  ssdMode.yml: |
    SSDMode: {{ .Values.SSDMode }} 
kind: ConfigMap
metadata:
  name: ssd-mode
  labels:
    app: ssd
    component: supplychain-preprocesser
{{ include "ssd.standard-labels" . | indent 4 }}
