apiVersion: v1
kind: Secret
metadata:
  name: supplychain-api
  labels:
    app: ssd
{{ include "oes.standard-labels" . | indent 4 }}
    component: oes-supplychain-api
stringData:
{{ (tpl (.Files.Glob "config/oes-supplychain-api/app-config.yaml").AsConfig . ) | indent 2 }}
