apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: oes-toolchain
{{ include "oes.standard-labels" . | indent 4 }}
  name: tool-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-toolchain
  template:
    metadata:
      labels:
        app: oes
        component: oes-toolchain
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.toolchain.annotations -}}
        {{ toYaml .Values.toolchain.annotations | nindent 8 }}
{{- end }}
    spec:
      containers:
        - name: tool-chain
          image: {{ template "toolchain.image" . }}
          ports:
            - containerPort: 8100
              protocol: TCP
          volumeMounts:
            - mountPath: /var/run
              name: docker-sock
            - name: scanresult
              mountPath: /tools/scanResult
            - name: tool-chain-volume
              mountPath: /tools/config/tool-chain.yaml
              subPath: tool-chain.yaml
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /health
              port: 8100
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      volumes:
        - name: scanresult
      {{- if .Values.noPvc }}
          emptyDir: {}
      {{- else }}
          persistentVolumeClaim:
            claimName: tool-chain
      {{- end }}
        - name: docker-sock
          hostPath:
            path: /var/run
            type: ""
        - name: tool-chain-volume
          configMap:
            name: tool-chain
            items:
              - key: tool-chain.yaml
                path: tool-chain.yaml
            defaultMode: 420
      restartPolicy: Always
      securityContext: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


